databases:
  - name: mydeezermongo
    databaseName: MyDeezerStats
    plan: free
    # 'engine' et 'envVars' ne sont plus nécessaires pour MongoDB sur Render
    # Render gère automatiquement ces paramètres

services:
  - type: web
    name: frontend
    dockerContext: ./3-FRONTEND/my-deezer-stats-front
    dockerfile: Dockerfile.prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_URL
        value: https://${SERVICE_NAME_API}.onrender.com
    healthCheckPath: /
    plan: free

  - type: web
    name: api
    dockerContext: ./2-BACKEND/src
    dockerfile: Dockerfile.prod
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: MongoDbSettings__ConnectionString
        fromDatabase:
          name: mydeezermongo
          property: connectionString
    plan: free