apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: benarais/mydeezerstats-api
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_CONNECTION_STRING
              value: "mongodb://root:example@mongo:27017"
