# Utilisez une image avec Node.js et npm
FROM node:18-alpine

WORKDIR /app

# Copie des fichiers de dépendances
COPY package.json package-lock.json ./

# Installation des dépendances (y compris devDependencies)
RUN npm install

# Copie du reste de l'application
COPY . .

# Expose le port 4200 (port par défaut d'Angular en dev)
EXPOSE 4200

# Commande pour lancer Angular en mode développement avec hot-reload
CMD ["npm", "start"]